
var __cov_6qwrUSE4DtfxZv9$6eMsWw = (Function('return this'))();
if (!__cov_6qwrUSE4DtfxZv9$6eMsWw.__coverage__) { __cov_6qwrUSE4DtfxZv9$6eMsWw.__coverage__ = {}; }
__cov_6qwrUSE4DtfxZv9$6eMsWw = __cov_6qwrUSE4DtfxZv9$6eMsWw.__coverage__;
if (!(__cov_6qwrUSE4DtfxZv9$6eMsWw['src/object.js'])) {
   __cov_6qwrUSE4DtfxZv9$6eMsWw['src/object.js'] = {"path":"src/object.js","s":{"1":0,"2":1,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"b":{"1":[0,0]},"f":{"1":0,"2":0,"3":0},"fnMap":{"1":{"name":"(anonymous_1)","line":7,"loc":{"start":{"line":7,"column":1},"end":{"line":7,"column":12}}},"2":{"name":"copyObject","line":9,"loc":{"start":{"line":9,"column":4},"end":{"line":9,"column":38}}},"3":{"name":"(anonymous_3)","line":25,"loc":{"start":{"line":25,"column":15},"end":{"line":25,"column":26}}}},"statementMap":{"1":{"start":{"line":7,"column":0},"end":{"line":33,"column":5}},"2":{"start":{"line":9,"column":4},"end":{"line":20,"column":5}},"3":{"start":{"line":10,"column":8},"end":{"line":10,"column":30}},"4":{"start":{"line":11,"column":8},"end":{"line":18,"column":9}},"5":{"start":{"line":16,"column":12},"end":{"line":17,"column":72}},"6":{"start":{"line":17,"column":16},"end":{"line":17,"column":72}},"7":{"start":{"line":19,"column":8},"end":{"line":19,"column":28}},"8":{"start":{"line":24,"column":4},"end":{"line":31,"column":7}},"9":{"start":{"line":26,"column":12},"end":{"line":26,"column":36}}},"branchMap":{"1":{"line":16,"type":"if","locations":[{"start":{"line":16,"column":12},"end":{"line":16,"column":12}},{"start":{"line":16,"column":12},"end":{"line":16,"column":12}}]}}};
}
__cov_6qwrUSE4DtfxZv9$6eMsWw = __cov_6qwrUSE4DtfxZv9$6eMsWw['src/object.js'];
__cov_6qwrUSE4DtfxZv9$6eMsWw.s['1']++;(function(){__cov_6qwrUSE4DtfxZv9$6eMsWw.f['1']++;function copyObject(sourceObject){__cov_6qwrUSE4DtfxZv9$6eMsWw.f['2']++;__cov_6qwrUSE4DtfxZv9$6eMsWw.s['3']++;var targetObject={};__cov_6qwrUSE4DtfxZv9$6eMsWw.s['4']++;for(var propertyName in sourceObject){__cov_6qwrUSE4DtfxZv9$6eMsWw.s['5']++;if(typeof sourceObject[propertyName]!=='function'){__cov_6qwrUSE4DtfxZv9$6eMsWw.b['1'][0]++;__cov_6qwrUSE4DtfxZv9$6eMsWw.s['6']++;targetObject[propertyName]=sourceObject[propertyName];}else{__cov_6qwrUSE4DtfxZv9$6eMsWw.b['1'][1]++;}}__cov_6qwrUSE4DtfxZv9$6eMsWw.s['7']++;return targetObject;}__cov_6qwrUSE4DtfxZv9$6eMsWw.s['8']++;Object.defineProperty(Object.prototype,'copy',{value:function(){__cov_6qwrUSE4DtfxZv9$6eMsWw.f['3']++;__cov_6qwrUSE4DtfxZv9$6eMsWw.s['9']++;return copyObject(this);},writable:true,configurable:true,enumerable:false});}());
