
var __cov_6qwrUSE4DtfxZv9$6eMsWw = (Function('return this'))();
if (!__cov_6qwrUSE4DtfxZv9$6eMsWw.__coverage__) { __cov_6qwrUSE4DtfxZv9$6eMsWw.__coverage__ = {}; }
__cov_6qwrUSE4DtfxZv9$6eMsWw = __cov_6qwrUSE4DtfxZv9$6eMsWw.__coverage__;
if (!(__cov_6qwrUSE4DtfxZv9$6eMsWw['src/object.js'])) {
   __cov_6qwrUSE4DtfxZv9$6eMsWw['src/object.js'] = {"path":"src/object.js","s":{"1":0,"2":1,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0,"10":0,"11":0,"12":0,"13":0},"b":{"1":[0,0]},"f":{"1":0,"2":0,"3":0,"4":0,"5":0},"fnMap":{"1":{"name":"(anonymous_1)","line":9,"loc":{"start":{"line":9,"column":1},"end":{"line":9,"column":12}}},"2":{"name":"copyObject","line":11,"loc":{"start":{"line":11,"column":4},"end":{"line":11,"column":38}}},"3":{"name":"(anonymous_3)","line":27,"loc":{"start":{"line":27,"column":15},"end":{"line":27,"column":26}}},"4":{"name":"(anonymous_4)","line":37,"loc":{"start":{"line":37,"column":15},"end":{"line":37,"column":26}}},"5":{"name":"(anonymous_5)","line":46,"loc":{"start":{"line":46,"column":15},"end":{"line":46,"column":26}}}},"statementMap":{"1":{"start":{"line":9,"column":0},"end":{"line":54,"column":5}},"2":{"start":{"line":11,"column":4},"end":{"line":22,"column":5}},"3":{"start":{"line":12,"column":8},"end":{"line":12,"column":30}},"4":{"start":{"line":13,"column":8},"end":{"line":20,"column":9}},"5":{"start":{"line":18,"column":12},"end":{"line":19,"column":72}},"6":{"start":{"line":19,"column":16},"end":{"line":19,"column":72}},"7":{"start":{"line":21,"column":8},"end":{"line":21,"column":28}},"8":{"start":{"line":26,"column":4},"end":{"line":33,"column":7}},"9":{"start":{"line":28,"column":12},"end":{"line":28,"column":36}},"10":{"start":{"line":36,"column":4},"end":{"line":43,"column":7}},"11":{"start":{"line":38,"column":12},"end":{"line":38,"column":77}},"12":{"start":{"line":45,"column":4},"end":{"line":52,"column":7}},"13":{"start":{"line":47,"column":12},"end":{"line":47,"column":46}}},"branchMap":{"1":{"line":18,"type":"if","locations":[{"start":{"line":18,"column":12},"end":{"line":18,"column":12}},{"start":{"line":18,"column":12},"end":{"line":18,"column":12}}]}}};
}
__cov_6qwrUSE4DtfxZv9$6eMsWw = __cov_6qwrUSE4DtfxZv9$6eMsWw['src/object.js'];
__cov_6qwrUSE4DtfxZv9$6eMsWw.s['1']++;(function(){__cov_6qwrUSE4DtfxZv9$6eMsWw.f['1']++;function copyObject(sourceObject){__cov_6qwrUSE4DtfxZv9$6eMsWw.f['2']++;__cov_6qwrUSE4DtfxZv9$6eMsWw.s['3']++;var targetObject={};__cov_6qwrUSE4DtfxZv9$6eMsWw.s['4']++;for(var propertyName in sourceObject){__cov_6qwrUSE4DtfxZv9$6eMsWw.s['5']++;if(typeof sourceObject[propertyName]!=='function'){__cov_6qwrUSE4DtfxZv9$6eMsWw.b['1'][0]++;__cov_6qwrUSE4DtfxZv9$6eMsWw.s['6']++;targetObject[propertyName]=sourceObject[propertyName];}else{__cov_6qwrUSE4DtfxZv9$6eMsWw.b['1'][1]++;}}__cov_6qwrUSE4DtfxZv9$6eMsWw.s['7']++;return targetObject;}__cov_6qwrUSE4DtfxZv9$6eMsWw.s['8']++;Object.defineProperty(Object.prototype,'copy',{value:function(){__cov_6qwrUSE4DtfxZv9$6eMsWw.f['3']++;__cov_6qwrUSE4DtfxZv9$6eMsWw.s['9']++;return copyObject(this);},writable:true,configurable:true,enumerable:false});__cov_6qwrUSE4DtfxZv9$6eMsWw.s['10']++;Object.defineProperty(Object.prototype,'isArray',{value:function(){__cov_6qwrUSE4DtfxZv9$6eMsWw.f['4']++;__cov_6qwrUSE4DtfxZv9$6eMsWw.s['11']++;return Object.prototype.toString.call(this)==='[object Array]';},writable:true,configurable:true,enumerable:false});__cov_6qwrUSE4DtfxZv9$6eMsWw.s['12']++;Object.defineProperty(Object.prototype,'isFunction',{value:function(){__cov_6qwrUSE4DtfxZv9$6eMsWw.f['5']++;__cov_6qwrUSE4DtfxZv9$6eMsWw.s['13']++;return typeof this==='function';},writable:true,configurable:true,enumerable:false});}());
